services:
  api:
    container_name: my_portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn build'
  pg:
    container_name: kenzie_db
    image: postgres
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - 5432:5432
