services:
  api:
    container_name: myAPI
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn build && yarn dev'
  pg:
    container_name: myDb
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5433:5432
